/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as BuyYoutubeViewsRouteImport } from './routes/buy-youtube-views'
import { Route as BuyYoutubeSubscribersRouteImport } from './routes/buy-youtube-subscribers'
import { Route as BuyYoutubeLikesRouteImport } from './routes/buy-youtube-likes'
import { Route as BuyXFollowersRouteImport } from './routes/buy-x-followers'
import { Route as BuyTwitterFollowersRouteImport } from './routes/buy-twitter-followers'
import { Route as BuyTwitchViewsRouteImport } from './routes/buy-twitch-views'
import { Route as BuyTwitchFollowersRouteImport } from './routes/buy-twitch-followers'
import { Route as BuyTrustpilotReviewsRouteImport } from './routes/buy-trustpilot-reviews'
import { Route as BuyTiktokViewsRouteImport } from './routes/buy-tiktok-views'
import { Route as BuyTiktokLikesRouteImport } from './routes/buy-tiktok-likes'
import { Route as BuyTiktokFollowersRouteImport } from './routes/buy-tiktok-followers'
import { Route as BuySpotifyPlaysRouteImport } from './routes/buy-spotify-plays'
import { Route as BuySpotifyFollowersRouteImport } from './routes/buy-spotify-followers'
import { Route as BuySoundcloudPlaysRouteImport } from './routes/buy-soundcloud-plays'
import { Route as BuyLinkedinConnectionsRouteImport } from './routes/buy-linkedin-connections'
import { Route as BuyKickFollowersRouteImport } from './routes/buy-kick-followers'
import { Route as BuyInstagramViewsRouteImport } from './routes/buy-instagram-views'
import { Route as BuyInstagramLikesRouteImport } from './routes/buy-instagram-likes'
import { Route as BuyInstagramFollowersRouteImport } from './routes/buy-instagram-followers'
import { Route as BuyGoogleReviewsRouteImport } from './routes/buy-google-reviews'
import { Route as BuyFacebookLikesRouteImport } from './routes/buy-facebook-likes'
import { Route as BuyFacebookFollowersRouteImport } from './routes/buy-facebook-followers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyYoutubeViewsRoute = BuyYoutubeViewsRouteImport.update({
  id: '/buy-youtube-views',
  path: '/buy-youtube-views',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyYoutubeSubscribersRoute = BuyYoutubeSubscribersRouteImport.update({
  id: '/buy-youtube-subscribers',
  path: '/buy-youtube-subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyYoutubeLikesRoute = BuyYoutubeLikesRouteImport.update({
  id: '/buy-youtube-likes',
  path: '/buy-youtube-likes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyXFollowersRoute = BuyXFollowersRouteImport.update({
  id: '/buy-x-followers',
  path: '/buy-x-followers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTwitterFollowersRoute = BuyTwitterFollowersRouteImport.update({
  id: '/buy-twitter-followers',
  path: '/buy-twitter-followers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTwitchViewsRoute = BuyTwitchViewsRouteImport.update({
  id: '/buy-twitch-views',
  path: '/buy-twitch-views',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTwitchFollowersRoute = BuyTwitchFollowersRouteImport.update({
  id: '/buy-twitch-followers',
  path: '/buy-twitch-followers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTrustpilotReviewsRoute = BuyTrustpilotReviewsRouteImport.update({
  id: '/buy-trustpilot-reviews',
  path: '/buy-trustpilot-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTiktokViewsRoute = BuyTiktokViewsRouteImport.update({
  id: '/buy-tiktok-views',
  path: '/buy-tiktok-views',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTiktokLikesRoute = BuyTiktokLikesRouteImport.update({
  id: '/buy-tiktok-likes',
  path: '/buy-tiktok-likes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTiktokFollowersRoute = BuyTiktokFollowersRouteImport.update({
  id: '/buy-tiktok-followers',
  path: '/buy-tiktok-followers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuySpotifyPlaysRoute = BuySpotifyPlaysRouteImport.update({
  id: '/buy-spotify-plays',
  path: '/buy-spotify-plays',
  getParentRoute: () => rootRouteImport,
} as any)
const BuySpotifyFollowersRoute = BuySpotifyFollowersRouteImport.update({
  id: '/buy-spotify-followers',
  path: '/buy-spotify-followers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuySoundcloudPlaysRoute = BuySoundcloudPlaysRouteImport.update({
  id: '/buy-soundcloud-plays',
  path: '/buy-soundcloud-plays',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyLinkedinConnectionsRoute = BuyLinkedinConnectionsRouteImport.update({
  id: '/buy-linkedin-connections',
  path: '/buy-linkedin-connections',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyKickFollowersRoute = BuyKickFollowersRouteImport.update({
  id: '/buy-kick-followers',
  path: '/buy-kick-followers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyInstagramViewsRoute = BuyInstagramViewsRouteImport.update({
  id: '/buy-instagram-views',
  path: '/buy-instagram-views',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyInstagramLikesRoute = BuyInstagramLikesRouteImport.update({
  id: '/buy-instagram-likes',
  path: '/buy-instagram-likes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyInstagramFollowersRoute = BuyInstagramFollowersRouteImport.update({
  id: '/buy-instagram-followers',
  path: '/buy-instagram-followers',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyGoogleReviewsRoute = BuyGoogleReviewsRouteImport.update({
  id: '/buy-google-reviews',
  path: '/buy-google-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyFacebookLikesRoute = BuyFacebookLikesRouteImport.update({
  id: '/buy-facebook-likes',
  path: '/buy-facebook-likes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyFacebookFollowersRoute = BuyFacebookFollowersRouteImport.update({
  id: '/buy-facebook-followers',
  path: '/buy-facebook-followers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/buy-facebook-followers': typeof BuyFacebookFollowersRoute
  '/buy-facebook-likes': typeof BuyFacebookLikesRoute
  '/buy-google-reviews': typeof BuyGoogleReviewsRoute
  '/buy-instagram-followers': typeof BuyInstagramFollowersRoute
  '/buy-instagram-likes': typeof BuyInstagramLikesRoute
  '/buy-instagram-views': typeof BuyInstagramViewsRoute
  '/buy-kick-followers': typeof BuyKickFollowersRoute
  '/buy-linkedin-connections': typeof BuyLinkedinConnectionsRoute
  '/buy-soundcloud-plays': typeof BuySoundcloudPlaysRoute
  '/buy-spotify-followers': typeof BuySpotifyFollowersRoute
  '/buy-spotify-plays': typeof BuySpotifyPlaysRoute
  '/buy-tiktok-followers': typeof BuyTiktokFollowersRoute
  '/buy-tiktok-likes': typeof BuyTiktokLikesRoute
  '/buy-tiktok-views': typeof BuyTiktokViewsRoute
  '/buy-trustpilot-reviews': typeof BuyTrustpilotReviewsRoute
  '/buy-twitch-followers': typeof BuyTwitchFollowersRoute
  '/buy-twitch-views': typeof BuyTwitchViewsRoute
  '/buy-twitter-followers': typeof BuyTwitterFollowersRoute
  '/buy-x-followers': typeof BuyXFollowersRoute
  '/buy-youtube-likes': typeof BuyYoutubeLikesRoute
  '/buy-youtube-subscribers': typeof BuyYoutubeSubscribersRoute
  '/buy-youtube-views': typeof BuyYoutubeViewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/buy-facebook-followers': typeof BuyFacebookFollowersRoute
  '/buy-facebook-likes': typeof BuyFacebookLikesRoute
  '/buy-google-reviews': typeof BuyGoogleReviewsRoute
  '/buy-instagram-followers': typeof BuyInstagramFollowersRoute
  '/buy-instagram-likes': typeof BuyInstagramLikesRoute
  '/buy-instagram-views': typeof BuyInstagramViewsRoute
  '/buy-kick-followers': typeof BuyKickFollowersRoute
  '/buy-linkedin-connections': typeof BuyLinkedinConnectionsRoute
  '/buy-soundcloud-plays': typeof BuySoundcloudPlaysRoute
  '/buy-spotify-followers': typeof BuySpotifyFollowersRoute
  '/buy-spotify-plays': typeof BuySpotifyPlaysRoute
  '/buy-tiktok-followers': typeof BuyTiktokFollowersRoute
  '/buy-tiktok-likes': typeof BuyTiktokLikesRoute
  '/buy-tiktok-views': typeof BuyTiktokViewsRoute
  '/buy-trustpilot-reviews': typeof BuyTrustpilotReviewsRoute
  '/buy-twitch-followers': typeof BuyTwitchFollowersRoute
  '/buy-twitch-views': typeof BuyTwitchViewsRoute
  '/buy-twitter-followers': typeof BuyTwitterFollowersRoute
  '/buy-x-followers': typeof BuyXFollowersRoute
  '/buy-youtube-likes': typeof BuyYoutubeLikesRoute
  '/buy-youtube-subscribers': typeof BuyYoutubeSubscribersRoute
  '/buy-youtube-views': typeof BuyYoutubeViewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/buy-facebook-followers': typeof BuyFacebookFollowersRoute
  '/buy-facebook-likes': typeof BuyFacebookLikesRoute
  '/buy-google-reviews': typeof BuyGoogleReviewsRoute
  '/buy-instagram-followers': typeof BuyInstagramFollowersRoute
  '/buy-instagram-likes': typeof BuyInstagramLikesRoute
  '/buy-instagram-views': typeof BuyInstagramViewsRoute
  '/buy-kick-followers': typeof BuyKickFollowersRoute
  '/buy-linkedin-connections': typeof BuyLinkedinConnectionsRoute
  '/buy-soundcloud-plays': typeof BuySoundcloudPlaysRoute
  '/buy-spotify-followers': typeof BuySpotifyFollowersRoute
  '/buy-spotify-plays': typeof BuySpotifyPlaysRoute
  '/buy-tiktok-followers': typeof BuyTiktokFollowersRoute
  '/buy-tiktok-likes': typeof BuyTiktokLikesRoute
  '/buy-tiktok-views': typeof BuyTiktokViewsRoute
  '/buy-trustpilot-reviews': typeof BuyTrustpilotReviewsRoute
  '/buy-twitch-followers': typeof BuyTwitchFollowersRoute
  '/buy-twitch-views': typeof BuyTwitchViewsRoute
  '/buy-twitter-followers': typeof BuyTwitterFollowersRoute
  '/buy-x-followers': typeof BuyXFollowersRoute
  '/buy-youtube-likes': typeof BuyYoutubeLikesRoute
  '/buy-youtube-subscribers': typeof BuyYoutubeSubscribersRoute
  '/buy-youtube-views': typeof BuyYoutubeViewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/buy-facebook-followers'
    | '/buy-facebook-likes'
    | '/buy-google-reviews'
    | '/buy-instagram-followers'
    | '/buy-instagram-likes'
    | '/buy-instagram-views'
    | '/buy-kick-followers'
    | '/buy-linkedin-connections'
    | '/buy-soundcloud-plays'
    | '/buy-spotify-followers'
    | '/buy-spotify-plays'
    | '/buy-tiktok-followers'
    | '/buy-tiktok-likes'
    | '/buy-tiktok-views'
    | '/buy-trustpilot-reviews'
    | '/buy-twitch-followers'
    | '/buy-twitch-views'
    | '/buy-twitter-followers'
    | '/buy-x-followers'
    | '/buy-youtube-likes'
    | '/buy-youtube-subscribers'
    | '/buy-youtube-views'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/buy-facebook-followers'
    | '/buy-facebook-likes'
    | '/buy-google-reviews'
    | '/buy-instagram-followers'
    | '/buy-instagram-likes'
    | '/buy-instagram-views'
    | '/buy-kick-followers'
    | '/buy-linkedin-connections'
    | '/buy-soundcloud-plays'
    | '/buy-spotify-followers'
    | '/buy-spotify-plays'
    | '/buy-tiktok-followers'
    | '/buy-tiktok-likes'
    | '/buy-tiktok-views'
    | '/buy-trustpilot-reviews'
    | '/buy-twitch-followers'
    | '/buy-twitch-views'
    | '/buy-twitter-followers'
    | '/buy-x-followers'
    | '/buy-youtube-likes'
    | '/buy-youtube-subscribers'
    | '/buy-youtube-views'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/auth'
    | '/buy-facebook-followers'
    | '/buy-facebook-likes'
    | '/buy-google-reviews'
    | '/buy-instagram-followers'
    | '/buy-instagram-likes'
    | '/buy-instagram-views'
    | '/buy-kick-followers'
    | '/buy-linkedin-connections'
    | '/buy-soundcloud-plays'
    | '/buy-spotify-followers'
    | '/buy-spotify-plays'
    | '/buy-tiktok-followers'
    | '/buy-tiktok-likes'
    | '/buy-tiktok-views'
    | '/buy-trustpilot-reviews'
    | '/buy-twitch-followers'
    | '/buy-twitch-views'
    | '/buy-twitter-followers'
    | '/buy-x-followers'
    | '/buy-youtube-likes'
    | '/buy-youtube-subscribers'
    | '/buy-youtube-views'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  BuyFacebookFollowersRoute: typeof BuyFacebookFollowersRoute
  BuyFacebookLikesRoute: typeof BuyFacebookLikesRoute
  BuyGoogleReviewsRoute: typeof BuyGoogleReviewsRoute
  BuyInstagramFollowersRoute: typeof BuyInstagramFollowersRoute
  BuyInstagramLikesRoute: typeof BuyInstagramLikesRoute
  BuyInstagramViewsRoute: typeof BuyInstagramViewsRoute
  BuyKickFollowersRoute: typeof BuyKickFollowersRoute
  BuyLinkedinConnectionsRoute: typeof BuyLinkedinConnectionsRoute
  BuySoundcloudPlaysRoute: typeof BuySoundcloudPlaysRoute
  BuySpotifyFollowersRoute: typeof BuySpotifyFollowersRoute
  BuySpotifyPlaysRoute: typeof BuySpotifyPlaysRoute
  BuyTiktokFollowersRoute: typeof BuyTiktokFollowersRoute
  BuyTiktokLikesRoute: typeof BuyTiktokLikesRoute
  BuyTiktokViewsRoute: typeof BuyTiktokViewsRoute
  BuyTrustpilotReviewsRoute: typeof BuyTrustpilotReviewsRoute
  BuyTwitchFollowersRoute: typeof BuyTwitchFollowersRoute
  BuyTwitchViewsRoute: typeof BuyTwitchViewsRoute
  BuyTwitterFollowersRoute: typeof BuyTwitterFollowersRoute
  BuyXFollowersRoute: typeof BuyXFollowersRoute
  BuyYoutubeLikesRoute: typeof BuyYoutubeLikesRoute
  BuyYoutubeSubscribersRoute: typeof BuyYoutubeSubscribersRoute
  BuyYoutubeViewsRoute: typeof BuyYoutubeViewsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-youtube-views': {
      id: '/buy-youtube-views'
      path: '/buy-youtube-views'
      fullPath: '/buy-youtube-views'
      preLoaderRoute: typeof BuyYoutubeViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-youtube-subscribers': {
      id: '/buy-youtube-subscribers'
      path: '/buy-youtube-subscribers'
      fullPath: '/buy-youtube-subscribers'
      preLoaderRoute: typeof BuyYoutubeSubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-youtube-likes': {
      id: '/buy-youtube-likes'
      path: '/buy-youtube-likes'
      fullPath: '/buy-youtube-likes'
      preLoaderRoute: typeof BuyYoutubeLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-x-followers': {
      id: '/buy-x-followers'
      path: '/buy-x-followers'
      fullPath: '/buy-x-followers'
      preLoaderRoute: typeof BuyXFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-twitter-followers': {
      id: '/buy-twitter-followers'
      path: '/buy-twitter-followers'
      fullPath: '/buy-twitter-followers'
      preLoaderRoute: typeof BuyTwitterFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-twitch-views': {
      id: '/buy-twitch-views'
      path: '/buy-twitch-views'
      fullPath: '/buy-twitch-views'
      preLoaderRoute: typeof BuyTwitchViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-twitch-followers': {
      id: '/buy-twitch-followers'
      path: '/buy-twitch-followers'
      fullPath: '/buy-twitch-followers'
      preLoaderRoute: typeof BuyTwitchFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-trustpilot-reviews': {
      id: '/buy-trustpilot-reviews'
      path: '/buy-trustpilot-reviews'
      fullPath: '/buy-trustpilot-reviews'
      preLoaderRoute: typeof BuyTrustpilotReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-tiktok-views': {
      id: '/buy-tiktok-views'
      path: '/buy-tiktok-views'
      fullPath: '/buy-tiktok-views'
      preLoaderRoute: typeof BuyTiktokViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-tiktok-likes': {
      id: '/buy-tiktok-likes'
      path: '/buy-tiktok-likes'
      fullPath: '/buy-tiktok-likes'
      preLoaderRoute: typeof BuyTiktokLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-tiktok-followers': {
      id: '/buy-tiktok-followers'
      path: '/buy-tiktok-followers'
      fullPath: '/buy-tiktok-followers'
      preLoaderRoute: typeof BuyTiktokFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-spotify-plays': {
      id: '/buy-spotify-plays'
      path: '/buy-spotify-plays'
      fullPath: '/buy-spotify-plays'
      preLoaderRoute: typeof BuySpotifyPlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-spotify-followers': {
      id: '/buy-spotify-followers'
      path: '/buy-spotify-followers'
      fullPath: '/buy-spotify-followers'
      preLoaderRoute: typeof BuySpotifyFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-soundcloud-plays': {
      id: '/buy-soundcloud-plays'
      path: '/buy-soundcloud-plays'
      fullPath: '/buy-soundcloud-plays'
      preLoaderRoute: typeof BuySoundcloudPlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-linkedin-connections': {
      id: '/buy-linkedin-connections'
      path: '/buy-linkedin-connections'
      fullPath: '/buy-linkedin-connections'
      preLoaderRoute: typeof BuyLinkedinConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-kick-followers': {
      id: '/buy-kick-followers'
      path: '/buy-kick-followers'
      fullPath: '/buy-kick-followers'
      preLoaderRoute: typeof BuyKickFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-instagram-views': {
      id: '/buy-instagram-views'
      path: '/buy-instagram-views'
      fullPath: '/buy-instagram-views'
      preLoaderRoute: typeof BuyInstagramViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-instagram-likes': {
      id: '/buy-instagram-likes'
      path: '/buy-instagram-likes'
      fullPath: '/buy-instagram-likes'
      preLoaderRoute: typeof BuyInstagramLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-instagram-followers': {
      id: '/buy-instagram-followers'
      path: '/buy-instagram-followers'
      fullPath: '/buy-instagram-followers'
      preLoaderRoute: typeof BuyInstagramFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-google-reviews': {
      id: '/buy-google-reviews'
      path: '/buy-google-reviews'
      fullPath: '/buy-google-reviews'
      preLoaderRoute: typeof BuyGoogleReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-facebook-likes': {
      id: '/buy-facebook-likes'
      path: '/buy-facebook-likes'
      fullPath: '/buy-facebook-likes'
      preLoaderRoute: typeof BuyFacebookLikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-facebook-followers': {
      id: '/buy-facebook-followers'
      path: '/buy-facebook-followers'
      fullPath: '/buy-facebook-followers'
      preLoaderRoute: typeof BuyFacebookFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  BuyFacebookFollowersRoute: BuyFacebookFollowersRoute,
  BuyFacebookLikesRoute: BuyFacebookLikesRoute,
  BuyGoogleReviewsRoute: BuyGoogleReviewsRoute,
  BuyInstagramFollowersRoute: BuyInstagramFollowersRoute,
  BuyInstagramLikesRoute: BuyInstagramLikesRoute,
  BuyInstagramViewsRoute: BuyInstagramViewsRoute,
  BuyKickFollowersRoute: BuyKickFollowersRoute,
  BuyLinkedinConnectionsRoute: BuyLinkedinConnectionsRoute,
  BuySoundcloudPlaysRoute: BuySoundcloudPlaysRoute,
  BuySpotifyFollowersRoute: BuySpotifyFollowersRoute,
  BuySpotifyPlaysRoute: BuySpotifyPlaysRoute,
  BuyTiktokFollowersRoute: BuyTiktokFollowersRoute,
  BuyTiktokLikesRoute: BuyTiktokLikesRoute,
  BuyTiktokViewsRoute: BuyTiktokViewsRoute,
  BuyTrustpilotReviewsRoute: BuyTrustpilotReviewsRoute,
  BuyTwitchFollowersRoute: BuyTwitchFollowersRoute,
  BuyTwitchViewsRoute: BuyTwitchViewsRoute,
  BuyTwitterFollowersRoute: BuyTwitterFollowersRoute,
  BuyXFollowersRoute: BuyXFollowersRoute,
  BuyYoutubeLikesRoute: BuyYoutubeLikesRoute,
  BuyYoutubeSubscribersRoute: BuyYoutubeSubscribersRoute,
  BuyYoutubeViewsRoute: BuyYoutubeViewsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
